# Regras minimas para funcionar
-dontobfuscate
-dontwarn **
-keep class MainKt { *; }
-keep class ** extends androidx.compose.** { *; }
-keep class io.ktor.** { *; }
-keep class kotlinx.serialization.** { *; }
-keep class org.jetbrains.skia.** { *; }
-keep class org.jetbrains.skiko.** { *; }
-keep class app.cash.sqldelight.** { *; }
-keep class com.sun.jna.** { *; }
-keepclassmembers class * { @kotlinx.serialization.Serializable *; }
